network:
  hashfunc:
    region: "ap-northeast-2"
    eip:
      hashfunc-nat-gateway-apne2-az1: {}
    vpc:
      hashfunc:
        cidrBlock: "10.16.0.0/16"
        internetGateway:
          hashfunc: {}
        natGateway:
          public-main-apne2-az1:
          - subnet: public-main-apne2-az1
            eip: hashfunc-nat-gateway-apne2-az1
        subnet:
          private-main:
          - cidrBlock: "10.16.16.0/22"
            availabilityZoneId: "apne2-az1"
          - cidrBlock: "10.16.20.0/22"
            availabilityZoneId: "apne2-az3"
          public-main:
          - cidrBlock: "10.16.0.0/22"
            availabilityZoneId: "apne2-az1"
          - cidrBlock: "10.16.4.0/22"
            availabilityZoneId: "apne2-az3"
        routeTable:
          private-main:
            subnet:
            - private-main-apne2-az1
            - private-main-apne2-az3
            route:
            - type: "NAT"
              cidr: "0.0.0.0/0"
              target: "public-main-apne2-az1"
          public-main:
            subnet:
            - public-main-apne2-az1
            - public-main-apne2-az3
            route:
            - type: "Internet"
              cidr: "0.0.0.0/0"
              target: "hashfunc"
