network:
  hashfunc:
    region: "ap-northeast-2"
    eip:
      hashfunc-nat-gateway: {}
    vpc:
      hashfunc:
        cidrBlock: "10.16.0.0/16"
        internetGateway:
          hashfunc: {}
        subnet:
          private-main:
          - cidrBlock: "10.16.16.0/22"
            availabilityZoneId: "apne2-az1"
          - cidrBlock: "10.16.20.0/22"
            availabilityZoneId: "apne2-az3"
          public-main:
          - cidrBlock: "10.16.0.0/22"
            availabilityZoneId: "apne2-az1"
          - cidrBlock: "10.16.4.0/22"
            availabilityZoneId: "apne2-az3"
