vpc:
  region: "ap-northeast-2"
  cidr: "10.192.0.0/16"
  subnets:
  - name: "private-main"
    scope: "private"
    cidrs:
    - cidr: "10.192.192.0/22"
      az_id: "apne2-az1"
    - cidr: "10.192.196.0/22"
      az_id: "apne2-az3"
  - name: "public-main"
    scope: "public"
    cidrs:
    - cidr: "10.192.0.0/22"
      az_id: "apne2-az1"
    - cidr: "10.192.4.0/22"
      az_id: "apne2-az3"
